### ISSUE TITLE
Peer-to-Peer Code Review

### ISSUE THREAD

**Issue by BenjaminSemah** [OybekKayumov/module1-project#4]
Morning Session Team
- Pedro Afonso
- Matovu Farid
- Benjamin Semah

## Suggestions
- Consider generating the partners card dynamically with JavaScript
- Consider making the footer responsive for different screen sizes.

**Comment by guerreiropedr0** [comment]
Hi Oybek, your project looks very good!
If there is any small things to change it would be the following:
- When you are in the about section, you could make the "About" in the navigation bar active, with the color orange! That would make it responsive and clean :smile:;
- In the README.md file I noticed your link to the MIT.md file doesn't work, I think that if you fix this, your overall project will look more professional.

Again, nice job, it looks amazing! 👍
